In [11]:
import pandas as pd

dictionary = pd.read_excel("../data/raw/Data Dictionary.xls")

dictionary

,Unnamed: 0,Unnamed: 1,Unnamed: 2
0,Variable Name,Description,Type
1,SeriousDlqin2yrs,Person experienced 90 days past due delinquenc...,Y/N
2,RevolvingUtilizationOfUnsecuredLines,Total balance on credit cards and personal lin...,percentage
3,age,Age of borrower in years,integer
4,NumberOfTime30-59DaysPastDueNotWorse,Number of times borrower has been 30-59 days p...,integer
5,DebtRatio,"Monthly debt payments, alimony,living costs di...",percentage
6,MonthlyIncome,Monthly income,real
7,NumberOfOpenCreditLinesAndLoans,Number of Open loans (installment like car loa...,integer
8,NumberOfTimes90DaysLate,Number of times borrower has been 90 days or m...,integer
9,NumberRealEstateLoansOrLines,Number of mortgage and real estate loans inclu...,integer
10,NumberOfTime60-89DaysPastDueNotWorse,Number of times borrower has been 60-89 days p...,integer
11,NumberOfDependents,Number of dependents in family excluding thems...,integer

In [21]:
# загружаем основной датасет и выводим информоцию для первичного анализа
train = pd.read_csv("../data/raw/cs-training.csv")

display(train.head())

print("Размер:", train.shape)

train.info()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

Размер: (150000, 12)
<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 12 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Unnamed: 0                            150000 non-null  int64
 1   SeriousDlqin2yrs                      150000 non-null  int64
 2   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 3   age                                   150000 non-null  int64
 4   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 5   DebtRatio                             150000 non-null  float64
 6   MonthlyIncome                         120269 non-null  float64
 7   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 8   NumberOfTimes90DaysLate               150000 non-null  int64
 9   NumberRealEstateLoansOrLines          150000 non-null  int64
 10  NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 11  NumberOfDependents                    146076 non-null  float64
dtypes: float64(4), int64(8)
memory usage: 13.7 MB

In [22]:
# собираем подробную информацию
print("Количество дубликатов:", train.duplicated().sum())

print("\nРаспределение целевой переменной:")
print(train['SeriousDlqin2yrs'].value_counts())

print('\nДоля классов:')
print(train['SeriousDlqin2yrs'].value_counts(normalize=True))

print('\nПропуски:')
missing = train.isna().sum()
missing_pct = train.isna().mean() * 100

missing_table = (
    pd.DataFrame({
        'missing_count':missing, 
        'missing_pct': missing_pct
    }).sort_values('missing_count', ascending=False)
)

display(missing_table)

Количество дубликатов: 0

Распределение целевой переменной:
SeriousDlqin2yrs
0    139974
1     10026
Name: count, dtype: int64

Доля классов:
SeriousDlqin2yrs
0    0.93316
1    0.06684
Name: proportion, dtype: float64

Пропуски:

                                      missing_count  missing_pct
MonthlyIncome                                 29731    19.820667
NumberOfDependents                             3924     2.616000
Unnamed: 0                                        0     0.000000
SeriousDlqin2yrs                                  0     0.000000
age                                               0     0.000000
RevolvingUtilizationOfUnsecuredLines              0     0.000000
DebtRatio                                         0     0.000000
NumberOfTime30-59DaysPastDueNotWorse              0     0.000000
NumberOfOpenCreditLinesAndLoans                   0     0.000000
NumberOfTimes90DaysLate                           0     0.000000
NumberRealEstateLoansOrLines                      0     0.000000
NumberOfTime60-89DaysPastDueNotWorse              0     0.000000